# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesdetail',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
